---
name: Functional Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  functional_tests:
    name: Setup malbolge
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        version: ['0.2']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Print version
        run: malbolge hello-world.mal
        shell: sh
